### ISSUE TITLE
This jetson-ffmpeg donot surport codec flush

### ISSUE THREAD

**Issue by katehe** [Keylost/jetson-ffmpeg#42]
When I use this jetson-ffmpeg to decode files in Jetson,
If I seek to some pos, the nvmpi decoder spat out some old frames even though I had already called avcodec_flush_buffers.
I have confirmed that the flush interface is not implemented in nvmpi_dec.c
Does jetson-ffmpeg plan to support flush？

**Comment by gjrtimmer** [comment]
This is addressed in the [gjrtimmer/jetson-ffmpeg](https://github.com/gjrtimmer/jetson-ffmpeg) fork:

- **Issue**: gjrtimmer/jetson-ffmpeg#16
- **Commit**: [`1ce8918`](https://github.com/gjrtimmer/jetson-ffmpeg/commit/1ce8918)
- **Fix**: Implements `avcodec_flush_buffers()` for the nvmpi decoder — adds `nvmpi_decoder_flush()` to libnvmpi (V4L2 STREAMOFF/STREAMON cycle, frame pool drain, capture thread restart) and wires it as the FFmpeg `.flush` callback with extradata (SPS/PPS) re-priming. Decoder-only; encoder flush deferred pending new encode API.
- **Validated**: smoke-all.sh 7/7 FFmpeg versions (4.2–8.0), hw-decoder-flush suite on Orin

**Comment by gjrtimmer** [comment]
Codec flush (`avcodec_flush_buffers`) is implemented for both decoder and encoder in this fork ([gjrtimmer/jetson-ffmpeg](https://github.com/gjrtimmer/jetson-ffmpeg)). Tracked in [gjrtimmer#16](https://github.com/gjrtimmer/jetson-ffmpeg/issues/16), regression-tested via dedicated hardware test suites (`hw-decoder-flush.sh`, `hw-encoder-flush.sh`).

**Comment by mmusabfolio3** [comment]
hey @gjrtimmer thanks for sharing the fix, I am actually looking for encoder side flush and seems like its still not there yet in contrast to your last message indicating its been implemented for both encoder and decoder. Can you please clarify.
Thanks

**Comment by gjrtimmer** [comment]
Codec flush is supported in [gjrtimmer/jetson-ffmpeg](https://github.com/gjrtimmer/jetson-ffmpeg). The decoder and encoder both handle EOS/flush signaling:

- Decoder: `avcodec_flush_buffers` triggers V4L2 EOS on the output plane, the capture loop drains remaining frames, then buffers are recycled.
- Encoder: flush sets the `flushing` flag (atomic), sends a zero-size buffer to signal EOS, and the DQ callback collects final packets.

Available since v2.8.0, current release is v3.0.0 (FFmpeg 6.0–8.0). Regression-tested via hardware tests on Orin NX.

**Comment by gjrtimmer** [comment]
@mmusabfolio3 you're right — there's a distinction between two things here.

**EOS drain** (getting remaining packets out at end of encoding) is implemented and landing now with [gjrtimmer#15](https://github.com/gjrtimmer/jetson-ffmpeg/issues/15). If you call `send_frame(NULL)` and then keep pulling `receive_packet()`, you'll get all buffered packets before EOF. This covers the typical "finish encoding cleanly" use case.

**Mid-stream encoder reset** via `avcodec_flush_buffers()` (resetting the encoder without close/reopen — for seeks, segment-based encoding, etc.) is not yet implemented. The decoder has this, the encoder doesn't. I've opened [gjrtimmer#45](https://github.com/gjrtimmer/jetson-ffmpeg/issues/45) to track it. It's on the roadmap but new FFmpeg version support comes first since that has broader impact. In the meantime you can work around it by closing and reopening the codec context.

What's your specific use case? That would help me figure out which of the two you actually need; please comment in [gjrtimmer#45](https://github.com/gjrtimmer/jetson-ffmpeg/issues/45).
